load("@rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "Navigation",
    srcs = [
        "Navigator.swift",
    ],
    module_name = "Navigation",
    visibility = ["//visibility:public"],
)


