load("@rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "Settings",
    srcs = [
        "SettingsViewController.swift",
        "SettingDetailViewController.swift",
    ],
    deps = [
        "//AppCore:AppCore",
    ],
    module_name = "Settings",
    visibility = ["//visibility:public"],
)


