load("@rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "ToDoDetail",
    srcs = [
        "ToDoDetailViewController.swift",
    ],
    deps = [
        "//AppCore:AppCore",
        "//ToDoList:ToDoList",
        "//Reminders:Reminders",
        "//Sharing:Sharing",
    ],
    module_name = "ToDoDetail",
    visibility = ["//visibility:public"],
)


