load("@rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "AppCore",
    srcs = [
        "ServiceLocator.swift",
        "ToDoModels.swift",
    ],
    module_name = "AppCore",
    visibility = ["//visibility:public"],
)


