load("@rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "ToDoList",
    srcs = [
        "ToDoListViewController.swift",
    ],
    deps = [
        "//AppCore:AppCore",
    ],
    module_name = "ToDoList",
    visibility = ["//visibility:public"],
)


