load("@rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "Reminders",
    srcs = [
        "ReminderViewController.swift",
    ],
    deps = [
        "//AppCore:AppCore",
    ],
    module_name = "Reminders",
    visibility = ["//visibility:public"],
)


